site_name: Manuel d'exemple
site_description: Manuel d'exemple embarqué par l'image docker
site_dir: Manuel d'exemple
site_url: ''

docs_dir: 'content'

theme:
  name: material
  custom_dir: content/_overrides
  language: fr
  include_sidebar: true
  favicon: assets/img/favicon.ico
  logo: assets/img/logo.png
  font: false

  features:
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - content.tabs.link

  palette:
      # Palette toggle for light mode
    - scheme: default
      primary: blue grey  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      accent: teal  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
      toggle:
        icon: material/toggle-switch
        name: Passer en mode sombre

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      accent: indigo  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
      toggle:
        icon: material/toggle-switch-off-outline
        name: Passer en mode lumineux

copyright: 'PingouInfini • Copyright &copy; 2023'

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - offline
  - minify:
      minify_html: true
  - pdf-export:
      verbose: true
      media_type: print
      combined: true
      combined_output_path: pdf/exported-site.pdf
      enabled_if_env: ENABLE_PDF_EXPORT
  - glightbox:
      skip_classes:
        - skip-lightbox

extra:
  generator: false
  version:
    provider: mike
    default: latest

extra_css:
  - assets/stylesheets/extra.css

nav:
  - 'Accueil': 'index.md'
  - 'Pages':
      - 'Lorem': 'general/page1.md'
      - 'Ipsum': 'general/page2.md'
      - 'Hodor': 'general/page3.md'
  - 'Images': 'general/images.md'
  - 'Hodor': 'hodor/page3.md' #reuse de la page3 [link] page3.md -> ../general/page3.md
